### ISSUE TITLE
Support selecting text

### ISSUE THREAD

**Issue by mattdeckard** [Limegrass/Wanicchou#58] opened 2019-08-05 11:03 UTC
It would be nice to be able to select the text in the definition view, e.g. so that users can more easily look up words via the Android context menu.

**Comment by Limegrass** [comment] 2019-08-05 18:03
Yeah, this was available in the beta version, but was put in the backlog when I reworked the UI. I'll push that up in the iterations.

Duplicate of #35

**Closed by Limegrass** 2019-08-05 18:03 UTC
